### ISSUE TITLE
As a user, I want to have an account so that I can play quiz game and  see my profile.

### ISSUE THREAD

**Issue by thanhvh99** [19team/INT2208-8-2019#22]

**Comment by lyminhnghia** [comment]
- [ ] Thiết kế cơ sở dữ liệu lưu thông tin người dùng (15 phút)

- [ ] Tạo giao diện đăng nhập, đăng kí cho người dùng (1 giờ)

- [ ] Làm backend cho trang đăng nhập, đăng kí bằng Node.js và cơ sở dữ liệu MySQL (2 giờ)

- [ ] Thực hiện liên kết các trang đăng nhập, đăng kí với phần backend đã hoàn thiện (30 phút)

- [ ] Thiết kế và làm trò chơi được lấy dữ liệu câu hỏi từ file json (2 giờ)

- [ ] Làm backend cho trò chơi để lấy trực tiếp dữ liệu câu hỏi từ cơ sở dữ liệu MySQL (3 giờ)

- [ ] Hợp nhất toàn bộ để sau khi đăng nhập người dùng mới có thể bắt đầu trò chơi (15 phút)

- [ ] Phát triển tính năng xem thông tin cá nhân và lưu điểm của người dùng (1 giờ)

- [ ] Thực hiện việc kiểm thử toàn bộ chương trình đã hoàn thành để tìm lỗi (30 phút)

**Comment by lyminhnghia** [comment]
**1. Đảm bảo tiêu chí INVEST:
*

**Comment by lyminhnghia** [comment]
1. Tasasdd

**Comment by lyminhnghia** [comment]
## 1. Đảm bảo tiêu chí INVEST:
