### ISSUE TITLE
As a player, I want to have a classic mode so that I can play easily.

### ISSUE THREAD

**Issue by thanhvh99** [19team/INT2208-8-2019#23]

**Comment by thanhvh99** [comment]
- [ ] Xây dựng nội dung cần có cho trang chủ

- [ ] Sắp xếp nội dung

- [ ] Giao diện hóa bằng html

- [ ] Áp dụng css5 để cải thiện giao diện

**Comment by hoangkimminh** [comment]
- [x] Thiết kế giao diện trang trò chơi cơ bản bằng HTML5 (2h)

- [ ] Cải thiện giao diện bằng CSS3 và Javascript (2h)

- [x] Hiển thị câu hỏi lên màn hình (30 phút)

- [x] Kiểm tra đáp án người dùng (15 phút)

- [ ] Tính điểm cho người chơi. Kết thúc màn chơi, hiển thị kết quả của màn chơi (1h)
